apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: payment
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: payment   
    spec:
      containers:
        - name: payment
          image: saithota9/payment:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 120
          #   periodSeconds: 5
          livenessProbe:
            # httpGet:
            #   path: /health
            #   port: 8080
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: payment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment  # Must match your Deployment name
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90  # Target 50% CPU usage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90 # Target 70% Memory usage
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment 
spec:
  selector:
    project: roboshop
    tier: backend
    component: payment 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080