apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping   
    spec:
      containers:
        - name: shipping
          image: saithota9/shipping:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "252Mi"
            limits:
              cpu: 150m"
              memory: "300Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 120
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   # tcpSocket:
          #   #   port: 8080
          #   initialDelaySeconds: 120
            # periodSeconds: 10
          envFrom:
            - configMapRef:
                name: shipping
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shiiping-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping # Must match your Deployment name
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Target 50% CPU usage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 # Target 70% Memory usage
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping 
spec:
  selector:
    project: roboshop
    tier: backend
    component: shipping 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080