apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: redis://redis:6379
  MONGO_URL: mongodb://mongodb:27017/users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: user
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: user   
    spec:
      containers:
        - name: user
          image: saithota9/user:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "90Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5
          livenessProbe:
            # httpGet:
            #   path: /health
            #   port: 8080
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: user
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user  # Must match your Deployment name
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90  # Target 50% CPU usage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90 # Target 70% Memory usage
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user 
spec:
  selector:
    project: roboshop
    tier: backend
    component: user 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080